import os
from datetime import datetime

MIN_POPULATION = os.environ["MIN_POPULATION"]
GEO_DB_REQUEST_LIMIT = os.environ["GEO_DB_REQUEST_LIMIT"]
DATA_BUCKET_NAME = os.environ["DATA_BUCKET_NAME"]
WEATHER_HOURLY_METRICS = os.environ["WEATHER_HOURLY_METRICS"]
WEATHER_DAILY_METRICS = os.environ["WEATHER_DAILY_METRICS"]
AIR_QUAL_HOURLY_METRICS = os.environ["AIR_QUAL_HOURLY_METRICS"]
METRICS_TIME_WINDOW_START = os.environ["METRICS_TIME_WINDOW_START"]
METRICS_TIME_WINDOW_END = os.environ["METRICS_TIME_WINDOW_END"]
AIR_QUAL_WINDOW_START = os.environ["AIR_QUAL_WINDOW_START"]
AIR_QUAL_WINDOW_END = os.environ["AIR_QUAL_WINDOW_END"]

RUN_GEODB = os.getenv("RUN_GEODB", False)
RUN_COUNT_CITIES = os.getenv("RUN_COUNT_CITIES", False)
RUN_IMF = os.getenv("RUN_IMF", False)
RUN_OPEN_METEO = os.getenv("RUN_OPEN_METEO", False)

now = datetime.now()
# FORMATTED_DATE = now.strftime("%d-%m-%Y")
FORMATTED_DATE = "11-10-2023"
